MCQ/MCQ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path("",include('MCQ_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MCQ/MCQ_app/urls.py
from django.urls import path

from . import views
from .views import SubjectList
app_name = 'MCQ_app'

urlpatterns = [
    path('subject/', views.subject_list, name='subject_list'),
    path('create_subject/', views.create_subject, name='create_subject'),
    path('create_mcq/<int:subject_id>/', views.create_mcq, name='create_mcq'),
    path('display_mcqs/<int:subject_id>/', views.display_mcqs, name='display_mcqs'),
    path('mcq-list/<int:subject_id>/', views.mcq_list, name='mcq_list'),
    path("score-view/",views.score_view,name='score_view'),
    path("",SubjectList.as_view(),name="subject_list"),
    path('get_scores/', views.display_all_Scores, name='display_all_Scores'),


  
]

MCQ/account/urls.py
from django.urls import path,include

from . import views
app_name = 'account'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', 
         views.register, name='register'),
    path('edit/',views.edit,name='edit'),
]

MCQ/MCQ_app/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.conf import settings

from account.models import Profile




# Create your models here.
creators_group,created = Group.objects.get_or_create(name='creators')
readers_group,created = Group.objects.get_or_create(name='readers')


class Subject(models.Model):
    name = models.CharField(max_length=100,unique=True)
   

    def __str__(self):
        return self.name
    
class MCQQuestion(models.Model):
    question_text = models.CharField(max_length=100)
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    option3 = models.CharField(max_length=100)
    option4 = models.CharField(max_length=100)
    correct_option = models.CharField(max_length=1,
                                      choices=[('1','Option 1'),
                                                            
                                                            ('2','Option 2'),('3','Option 3'),('4','Option 4')])
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text
    

class UserScore(models.Model):
    """
    Table to store user's score on each subject
    """
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    score = models.IntegerField()


    

MCQ/MCQ_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Subject, MCQQuestion

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name']

class MCQForm(forms.ModelForm):
    class Meta:
        model = MCQQuestion
        fields = ['subject', 'question_text', 
                  'option1', 'option2', 'option3', 'option4', 'correct_option']

class UserSubjectForm(forms.Form):
    user = forms.CharField(label='User',required=True)
    subject = forms.CharField(label='Subject',required=False)

    def clean_user(self):
        user_username = self.cleaned_data.get('user')
        try:
            user = User.objects.get(username=user_username)
        except User.DoesNotExist:
            raise forms.ValidationError('User does not exist')
        return user

MCQ/MCQ_app/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.core import serializers
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User

from json import dumps 
import json

from .models import Subject, MCQQuestion,UserScore
from .forms import SubjectForm, MCQForm,UserSubjectForm
from .decorators import custom_permission_required

def subject_list(request):
    subjects = Subject.objects.all()
    return render(request, 'subject_list.html', {'subjects': subjects})


@login_required
@custom_permission_required('MCQ_app.can_create_subject')
def create_subject(request):
    
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('MCQ_app:subject_list')
    else:
        form = SubjectForm()
    return render(request, 'create_subject.html', {'form': form})



@login_required
@custom_permission_required('MCQ_app.can_create_subject')
def create_mcq(request, subject_id):
    subject = Subject.objects.get(pk=subject_id)
    if request.method == 'POST':
        form = MCQForm(request.POST)
        if form.is_valid():
            mcq = form.save(commit=False)
            mcq.subject = subject
            mcq.save()
            if 'save_and_add_another' in request.POST:
                return redirect('MCQ_app:create_mcq',subject_id)
            else:
                return redirect('MCQ_app:subject_list')
    else:
        form = MCQForm(initial={'subject': subject})
    return render(request, 'create_mcq.html', {'form': form})


def display_mcqs(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    mcqs = MCQQuestion.objects.filter(subject=subject)    
    score = None

    if request.method == 'POST':
        form_data = request.POST
        print(form_data.values)

        correct_ans = [mcq.correct_option for mcq in mcqs]
        all_values = [values for key,values in form_data.items() if key != 'csrfmiddlewaretoken']
        score = sum(1 for i, j in zip(all_values,correct_ans) if i == j)

        print("Number of places with the same items:", score)
        return render(request,'display_score.html',{'score':score})

    return render(request, 'display_mcqs.html', {'subject': subject, 'mcqs': mcqs,'score': score})



@login_required
def mcq_list(request,subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    mcq_objects = MCQQuestion.objects.filter(subject=subject) 
    mcq_list = []

    for mcq in mcq_objects:
        mcq_item = {
            'question':mcq.question_text,
            'options':[mcq.option1,mcq.option2,mcq.option3,mcq.option4],
            'correct_answer':mcq.correct_option
        }

        mcq_list.append(mcq_item)

    the_subject = [{"subject":subject.name}]
    print(the_subject[0])
    dataJSON = dumps(mcq_list) 
    the_subject = dumps(the_subject)
    print(type(dataJSON))
    return render(request, 'mcq_list_2.html', {'data': dataJSON,'subject':the_subject}) 

@login_required
def score_view(request):
    if request.method == 'POST':
        post_data = json.loads(request.body)
        print(post_data)
        print(request.user)
        value = post_data['value']
        print(value)
        print(post_data['subject'])
        subject = get_object_or_404(Subject,name=post_data['subject'])
        print(f"The subject is {subject}")
        score_object = UserScore(user=request.user,
                                 subject=subject,
                                 score=post_data['value'])
        score_object.save()
       
        # Process the value as needed
        return JsonResponse({'message': 'Received value from JavaScript: {}'.format(value)})


#list all the subjects
class SubjectList(ListView):
    model = Subject
    template_name = 'subject_list_user.html'  # Specify the template name
    context_object_name = 'subject_list'  # Specify the context variable name for the list of objects

def display_all_Scores(request):
    if request.method=='POST':
        form = UserSubjectForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            user = User.objects.get(username=user)
            print("******************")
            print(user.id)
            subject = form.cleaned_data['subject']
            subject = Subject.objects.get(name=subject)
            print(subject.id)

            print("*********************")
            user_scores = UserScore.objects.filter(user=user.id,subject=subject.id)
            return render(request,'scores.html',{'user_scores':user_scores})
        
    else:
        form = UserSubjectForm()

    return render(request,'user_subject_form.html',{'form':form})


        

MCQ/MCQ_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Website{% endblock %}</title>
</head>
<body>

<div id="menu">
    <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <!-- Add more menu items as needed -->
        {% if request.user.is_authenticated %}
        <li>
            Hello {{request.user.first_name|default:request.user.username}}
        </li>
        <li>
            <a href="{% url 'account:logout'%}">
                Logout
            </a>
        </li>
        <li>
            <a href="{% url 'account:password_change'%}">Change-Password</a>
        </li>
        <li>
            <a href="{% url 'account:edit' %}">Edit Profile</a>
        </li>
        {% else %}
            <a href="{% url 'account:login' %}">Log-in</a>

        {% endif %}
    </ul>
</div>
{% if messages %}
    <p>Fuck</p>
    <ul>
        {% for message in messages %}
            <li>
                {{message|safe}}
                <a href="#">x</a>
            </li>

        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

MCQ/MCQ_app/templates/create_mcq.html
{% extends 'base.html' %}

{% block content %}
<h1>Create MCQ for {{ form.instance.subject.name }}</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
  <button type="submit" name="save_and_add_another">Save and Add Another</button>
</form>
{% endblock %}

MCQ/MCQ_app/templates/create_subject.html
{% extends 'base.html' %}


{% block content %}
<h1>Create Subject</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    
  </form>
{% endblock %}

MCQ/MCQ_app/templates/display_mcqs.html
{% extends 'base.html' %}

{% block content %}
<h1>MCQs for {{ subject.name }}</h1>
<form method="POST">
  {% csrf_token %}
  {% for mcq in mcqs %}
    <fieldset>
      <legend>{{ mcq.question_text }}</legend>
      <ul>
        <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="1"> {{ mcq.option1 }}</label></li>
        <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="2"> {{ mcq.option2 }}</label></li>
        <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="3"> {{ mcq.option3 }}</label></li>
        <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="4"> {{ mcq.option4 }}</label></li>
      </ul>
    </fieldset>
  {% endfor %}
  <input type="submit" value="Submit">
</form>
{% if score is not None %}
  <h2>Your Score: {{ score }}</h2>
{% endif %}
{% endblock %}

MCQ/MCQ_app/templates/display_score.html
{% extends 'base.html' %}

{% block content %}
 
{% if score is not None %}
<h2>Your Score: {{ score }}</h2>
{% endif %}
{% endblock %}

MCQ/MCQ_app/templates/mcq_list.html
<!DOCTYPE html> 
<body> 
	
    <div id="questions">
        <h3 id="theSubject"></h3>
        <h4 id="question"></h4>



        <div id="options">
          <input type="checkbox" id="option1" value="1" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option1"></label><br>

          <input type="checkbox" id="option2" value="2" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option2"></label><br>

          <input type="checkbox" id="option3" value="3" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option3"></label><br>

          <input type="checkbox" id="option4" value="4" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option4"></label><br>

        </div>
        

        <button id="next">Next</button>

    </div>
    <div id="score_div">
        <h4 id="score"></h4>
    </div>
    
    <form id="myForm">
        {% csrf_token %}
        <!-- Other form fields and content -->
    </form>
    


</body> 
</html> 
<script> 

	var data = JSON.parse("{{data|escapejs}}"); 
    var subject = JSON.parse("{{subject|escapejs}}"); 
    console.log(data);
    console.log(subject);
    const length = Object.keys(data).length;
   
    var count = 0;
    var score = 0;
    var flag = 0;
    let lastSelectedRadio = null;
    var quediv = document.getElementById('questions');
    const scoreid = document.getElementById('score_div');

    var subject_space = document.getElementById('theSubject');
    var question_space = document.getElementById('question');
    const next_button = document.getElementById('next');
    const option1 = document.querySelector('label[for="option1"]');
    const option2 = document.querySelector('label[for="option2"]');
    const option3 = document.querySelector('label[for="option3"]');
    const option4 = document.querySelector('label[for="option4"]');
    const buttons = document.getElementsByName("mcqoptions");
    

    subject_space.innerHTML = subject[0].subject;
 

    question_space.innerHTML = data[count].question;
    option1.innerHTML  = data[count].options[0];
    option2.innerHTML  = data[count].options[1];
    option3.innerHTML  = data[count].options[2];
    option4.innerHTML  = data[count].options[3];
    

    next_button.addEventListener('click', function() {

        console.log("next button fucked");
        if(data[count].correct_answer == lastSelectedRadio.value) {
                score++;
            }
            
            console.log("score: ")
            console.log(score);
       
        if(flag){
            console.log("fuck")

            quediv.style.display = "none";
            scoreid.innerHTML = score;
            sendDataToDjango(score);

        }

        if(!flag){
             
          // resetRadioButtons("mcqoptions");
          //  buttons.setAttribute('checked',false);
            count++;
            question_space.innerHTML = data[count].question;
            option1.innerHTML  = data[count].options[0];
            option2.innerHTML  = data[count].options[1];
            option3.innerHTML  = data[count].options[2];
            option4.innerHTML  = data[count].options[3];
            console.log("count:");
            console.log(count);
            
            lastSelectedRadio.checked = false;
            
            if(count === length - 1){
            flag = 1;
            }

        }

        
        
        
    
    
    });

    

function updateSelection(selectedRadio) {
  if (lastSelectedRadio) {
    lastSelectedRadio.checked = false;  // Unselect the previously selected radio button
  }

  lastSelectedRadio = selectedRadio;  // Update the last selected radio button
}



function sendDataToDjango(value) {
    
    console.log("here")
    console.log(document.getElementsByName('csrfmiddlewaretoken')[0].value)
  const csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;  // Get the CSRF token

  const data = {
    value: value,
    subject:subject[0].subject,
    csrfmiddlewaretoken: csrfToken
  };
  console.log("data")
  console.log(data)


  // Send a POST request to your Django view
  fetch('/score-view/', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-CSRFToken': csrfToken
    },
    body: JSON.stringify(data)
  })
  .then(response => {
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    console.log(response);
    return response.json();
  })
  .then(data => {
    console.log('Response from Django:', data);
  })
  .catch(error => {
    console.error('Error sending data to Django:', error);
  });
}

function resetRadioButtons(groupName) {
    const checkboxes = document.querySelectorAll(`input[name="${groupName}"]`);
    console.log("Resetting radio buttons");
    checkboxes.forEach(checkbox => {
        console.log("Resetting all the buttons");
        checkbox.checked = false;
    });
}


	
</script>

MCQ/MCQ_app/templates/mcq_list_2.html
{% extends 'base.html' %}
{% block content %}
<body> 
	
    <div id="questions">
        <h3 id="theSubject"></h3>
        <h4 id="question"></h4>



        <div id="options">
          <input type="radio" id="option1" value="1" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option1"></label><br>

          <input type="radio" id="option2" value="2" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option2"></label><br>

          <input type="radio" id="option3" value="3" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option3"></label><br>

          <input type="radio" id="option4" value="4" name="mcqoptions" onclick="updateSelection(this)">
          <label for="option4"></label><br>

        </div>
        

        <button id="next">Next</button>

    </div>
    <div id="score_div">
        <h4 id="score"></h4>
    </div>
    <div id="redirect">

    </div>

    <input type="text" id="countdownTextBox" readonly>

    <form id="myForm">
        {% csrf_token %}
        <!-- Other form fields and content -->
    </form>
    


</body> 
</html> 
<script> 

	var data = JSON.parse("{{data|escapejs}}"); 
    var subject = JSON.parse("{{subject|escapejs}}"); 
    console.log(data);
    console.log(subject);
    const length = Object.keys(data).length;
   
    var count = 0;
    var score = 0;
    var flag = 0;
    let lastSelectedRadio = null;
    var quediv = document.getElementById('questions');
    const scoreid = document.getElementById('score_div');

    var subject_space = document.getElementById('theSubject');
    var question_space = document.getElementById('question');
    const next_button = document.getElementById('next');
    const redirectDiv = document.getElementById('redirect');

    const option1 = document.querySelector('label[for="option1"]');
    const option2 = document.querySelector('label[for="option2"]');
    const option3 = document.querySelector('label[for="option3"]');
    const option4 = document.querySelector('label[for="option4"]');
    const buttons = document.getElementsByName("mcqoptions");
    

    subject_space.innerHTML = subject[0].subject;
 

    question_space.innerHTML = data[count].question;
    option1.innerHTML  = data[count].options[0];
    option2.innerHTML  = data[count].options[1];
    option3.innerHTML  = data[count].options[2];
    option4.innerHTML  = data[count].options[3];
    

    next_button.addEventListener('click', function() {

        

        console.log("next button fucked");
        if(data[count].correct_answer == lastSelectedRadio.value) {
                score++;
            }
            
            console.log("score: ")
            console.log(score);
       
        if(flag){
            console.log("fuck")

            quediv.style.display = "none";
            scoreid.innerHTML = score;
            sendDataToDjango(score);
            createButton();

        }

        if(!flag){
            
            count++;
            create_and_destroy_radio_buttons("mcqoptions",data[count].options[0],data[count].options[1],data[count].options[2],data[count].options[3]);
            
            question_space.innerHTML = data[count].question;
            // option1.innerHTML  = data[count].options[0];
            // option2.innerHTML  = data[count].options[1];
            // option3.innerHTML  = data[count].options[2];
            // option4.innerHTML  = data[count].options[3];
            console.log("count:");
            console.log(count);
            
            lastSelectedRadio.checked = false;
            
            if(count === length - 1){
            flag = 1;
            }

        }

        
        
        
    
    
    });

    

function updateSelection(selectedRadio) {
  if (lastSelectedRadio) {
    lastSelectedRadio.checked = false;  // Unselect the previously selected radio button
  }

  lastSelectedRadio = selectedRadio;  // Update the last selected radio button
}



function sendDataToDjango(value) {
    
    console.log("here")
    console.log(document.getElementsByName('csrfmiddlewaretoken')[0].value)
  const csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;  // Get the CSRF token

  const data = {
    value: value,
    subject:subject[0].subject,
    csrfmiddlewaretoken: csrfToken
  };
  console.log("data")
  console.log(data)


  // Send a POST request to your Django view
  fetch('/score-view/', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-CSRFToken': csrfToken
    },
    body: JSON.stringify(data)
  })
  .then(response => {
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    console.log(response);
    return response.json();
  })
  .then(data => {
    console.log('Response from Django:', data);
  })
  .catch(error => {
    console.error('Error sending data to Django:', error);
  });
}

function create_and_destroy_radio_buttons(name,a,b,c,d){
    const container = document.getElementById('options');
    const elements = document.querySelectorAll(`[name="${name}"]`);

  elements.forEach(element => {
    element.remove();
  });

  const brElements = container.querySelectorAll('br');

  brElements.forEach(br => {
    br.remove();
  });


  const brElement = document.createElement('br');
  
  
  const labels = container.querySelectorAll('label');

  labels.forEach(label => {
    label.remove();
  });

  const radioButton1 = document.createElement('input');
  radioButton1.type = 'radio';
  radioButton1.id = 'option1';
  radioButton1.value = '1';
  radioButton1.name = 'mcqoptions';
  radioButton1.onclick = function() {
    updateSelection(this);
  };

  // Append the radio button to the specified container
 
  container.appendChild(radioButton1);
  const label1 = document.createElement('label');
    label1.setAttribute('for', 'option1');
    label1.innerHTML = a;
  container.appendChild(label1);
 
  container.appendChild(document.createElement('br'));



  const radioButton2 = document.createElement('input');
  radioButton2.type = 'radio';
  radioButton2.id = 'option2';
  radioButton2.value = '2';
  radioButton2.name = 'mcqoptions';
  radioButton2.onclick = function() {
    updateSelection(this);
  };

  // Append the radio button to the specified container
  
  container.appendChild(radioButton2);
  const label2 = document.createElement('label');
    label2.setAttribute('for', 'option2');
    label2.innerHTML = b;
    container.appendChild(label2);
    
    container.appendChild(document.createElement('br'));

  const radioButton3 = document.createElement('input');
  radioButton3.type = 'radio';
  radioButton3.id = 'option3';
  radioButton3.value = '3';
  radioButton3.name = 'mcqoptions';
  radioButton3.onclick = function() {
    updateSelection(this);
  };

  // Append the radio button to the specified container
  
  container.appendChild(radioButton3);
  const label3 = document.createElement('label');
    label3.setAttribute('for', 'option3');
    console.log(c);
    label3.innerHTML = c;
    container.appendChild(label3);
    container.appendChild(document.createElement('br'));
    

  const radioButton4 = document.createElement('input');
  radioButton4.type = 'radio';
  radioButton4.id = 'option4';
  radioButton4.value = '4';
  radioButton4.name = 'mcqoptions';
  radioButton4.onclick = function() {
    updateSelection(this);
  };

  // Append the radio button to the specified container
  

  container.appendChild(radioButton4);
  const label4 = document.createElement('label');
    label4.setAttribute('for', 'option4');
    label4.innerHTML = d;
    container.appendChild(label4);
    container.appendChild(document.createElement('br'));
}

function createButton(){
  const redirectButton = document.createElement('button');
  redirectButton.innerHTML = "Go Home";
  redirectDiv.appendChild(redirectButton);
}


//code for timer
const countdownTimeInSeconds = 5;  
let timeRemaining = countdownTimeInSeconds;
// Function to update the timer display in the text box
function updateTimer() {
      const countdownTextBox = document.getElementById('countdownTextBox');
      countdownTextBox.value = `Time remaining: ${timeRemaining} seconds`;

      // Check if the timer has reached zero
      if (timeRemaining <= 0) {
        clearInterval(timerInterval);  // Stop the timer
        countdownTextBox.value = 'Time is up!';
      } else {
        timeRemaining--;
      }
    }

    // Update the timer every second
    const timerInterval = setInterval(updateTimer, 1000);
	
</script>

{% endblock %}

MCQ/MCQ_app/templates/mcq_question_template.html
{% extends 'base.html' %}

{% block content %}
<h1>MCQs for {{ subject.name }}</h1>
{% if question %}
    <h3>{{ question.question_text }}</h3>
    <!-- Display question options and form for submitting user's answer -->
    <!-- Adjust this based on your MCQQuestion model structure -->
    <form method="post">
        {% csrf_token %}
        <ul>
            <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="1"> {{ question.option1 }}</label></li>
            <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="2"> {{ question.option2 }}</label></li>
            <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="3"> {{ question.option3 }}</label></li>
            <li><label><input type="radio" name="mcq_{{ mcq.id }}" value="4"> {{ question.option4 }}</label></li>
          </ul>
        <button type="submit">Submit</button>
    </form>
    <hr>
    <p>Question {{ current_question_index}}+1 of {{ total_questions }}</p>
    <a href="{% url 'MCQ_app:next_question' subject_id %}">Next</a>
{% else %}
    <p>No more questions available.</p>
{% endif %}

{% endblock %}

MCQ/MCQ_app/templates/no_more_questions.html
<h1>Fuck</h1>

MCQ/MCQ_app/templates/scores.html
{% extends "base.html" %}

{% block title%}
<head>
    <title>Scores</title>
</head>
{% endblock %}

{% block content %}
<h2>Scores for User: {{ user.username }} and Subject: {{ user_subject }}</h2>
<ul>
    {% for score in user_scores %}
        <li>{{ score.score }}</li>
    {% endfor %}
</ul>
{% endblock %}

MCQ/MCQ_app/templates/subject_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Subjects</h1>
<ul>
  {% for subject in subjects %}
    <li>{{ subject.name }} - <a href="{% url 'MCQ_app:create_mcq' subject.id %}">Add MCQ</a></li>
  {% endfor %}
</ul>
<a href="{% url 'MCQ_app:create_subject' %}">Add Subject</a>
{% endblock %}

MCQ/MCQ_app/templates/subject_list_user.html
{% extends 'base.html' %}

{% block title%}
<head>
    <title>Subject List</title>
</head>
{% endblock %}

{% block content %}
<body>
    <h1>TEST</h1>
    <ul>
        {% for item in subject_list %}
            <li>{{ item.id }} - {{ item.name }}
                <a href="{% url 'MCQ_app:mcq_list' item.id %}">Take a Test</a>
            </li>
        {% endfor %}
    </ul>
</body>
{% endblock %}

MCQ/MCQ_app/templates/user_subject_form.html
{% extends 'base.html' %}
{% block title %}
<title>Enter user and subject</title>
{% endblock %}

{% block content %}
    <h2>Enter User and Subject</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}